### ISSUE TITLE
Using a MemCard Pro as an SD card adapter

### ISSUE THREAD

**Issue by papadonnystew** [paulocode/picostation#12]
Is this possible? I realize this might be more expensive overall, but if there is a possibility of only needing the Pico and a means of reading the card (MemCard Pro), and maybe leaving the optical drive functional, that would be awesome.

I love the nature of the PicoBoot mod for the GameCube, which leaves the optical drive functional if needed but also gives the option to boot games out of an SD card.

Amazing work so far, by the way. I'm very excited about the future of this project!

**Comment by airainchoc** [comment]
From what I understand, it shouldn't be possible in the current state of things.

The picostation intercepts CD related commands and replies to it, but it doesn't see anything else

**Comment by airainchoc** [comment]
From what I understand, it shouldn't be possible in the current state of things.

The picostation intercepts CD related commands and replies to it, but it doesn't see anything else
