### ISSUE TITLE
D1 Diode, Noob Question

### ISSUE THREAD

**Issue by Slypty** [paulocode/picostation#13]
Sorry for the noob question, but I'm afraid of frying something if I put the Diode D1 in the wrong orientation.
 I'm assuming the cathode end faces VSYS or Pin 37 on the RP2040?  Or, am I shunting power so that nothing reaches it, so that the Diode's cathode is facing the 7805?  
 
 Thanks

**Comment by airainchoc** [comment]
The cathode should be facing the Pico

https://github.com/paulocode/picostation_pcb/issues/4
