### ISSUE TITLE
Pin compatible ssb

### ISSUE THREAD

**Issue by mlalgjar** [paulocode/picostation#21]
Since the Pico station is pin compatible with the xstation qsb does that mean the xstation is pin compatible with the Pico station ssb? Like if I installed a Pico station using ssb can I swap it with an xstation?

**Comment by ramapcsx2** [comment]
The QSBs that have been designed with the xStation in mind should work with the picostation, yep.

**Comment by mlalgjar** [comment]
Thank you for your reply! Just to clarify what I mean, I have both an x station and Picostation. My question really is about cross-compatibility between both and if they're interchangeable, not just the main board but the each other's daughter boards (qsb vs slow solder boards.) 

Use case being if I hook up the slow solder board that came with the Pico station kit, could I then swap out the Pico board with the x station main board whenever I chose? Does pin compatibility ability go both ways?

**Comment by ramapcsx2** [comment]
In theory, yes. I say that to cover against unforeseen ..stuff, but it should be fine :)
