### ISSUE TITLE
about model compatibility

### ISSUE THREAD

**Issue by hex-spell** [paulocode/picostation#22]
I've been researching the psx internals and all, but I still can't figure out why the xstation QSB (or the SSB) are not compatible with pu-23. As far as I can see, they don't really need the parallel port.
This project gave me hope cause it is open source, I'm willing to do the research/development to make it compatible, but I don't know if it is even possible. Should I give up and find another model?

**Comment by ramapcsx2** [comment]
It is entirely not possible to use xStation/Picostation on anything later than PU-18. The combined chipset prevents it effectively.
It cannot be done, and there's no way to get around it :p

**Comment by hex-spell** [comment]
sad, ok closing this then

**Comment by ramapcsx2** [comment]
(Wait for mStation ;p)
